### pandas 모듈
- 참조: https://pandas.pydata.org/docs/getting_started/index.html#getting-started

In [1]:
#!pip install pandas

In [2]:
import pandas as pd
from numpy import random
import matplotlib.pyplot as plt

#### pandas.Series 구조

In [3]:
df1=pd.Series(['AAA', 'BBB', "CCC", "DDD"], name="Name")
print(df1)
print(type(df1))

0    AAA
1    BBB
2    CCC
3    DDD
Name: Name, dtype: object
<class 'pandas.core.series.Series'>

In [12]:
df2=pd.Series([33,28,45,41], name="Age")
print(df2)
print(type(df2))
df2=pd.DataFrame(df2)
print(df2)
print(type(df2))

0    33
1    28
2    45
3    41
Name: Age, dtype: int64
<class 'pandas.core.series.Series'>
   Age
0   33
1   28
2   45
3   41
<class 'pandas.core.frame.DataFrame'>

In [13]:
# 두개 이상의 데이터프레임 또는 시리즈 구조의 데이터를 병합할때 사용
# 병합방법: 행병합(행추가)-기본 => axis=0, 열병합(열추가) => axis=1

df0=pd.concat([df1, df2], axis=1)   # 기준인 df1에 df2를 열추가한 결과는 df0에 저장
df0

  Name  Age
0  AAA   33
1  BBB   28
2  CCC   45
3  DDD   41

### pandas.DataFrame 구조

In [14]:
# pandas.DataFrame 생성: 디셔너리 구조 이용

df1=pd.DataFrame({'Name':['AAA', 'BBB', "CCC", "DDD"],
                  'Age':[33,28,45,41], 
                  'Sex':['male', 'male', 'female', 'male']})
df1

  Name  Age     Sex
0  AAA   33    male
1  BBB   28    male
2  CCC   45  female
3  DDD   41    male

In [22]:
# pandas.DataFrame 생성: 리스트 구조 이용
# pandas.DataFrame([리스트 값], columns=[열이름 정의])
df1=pd.DataFrame([["AAA", 33, "male"],['BBB', 28, ], ['CCC', 45, "female"], 
                  ['DDD', 41, 'male']], columns=["Name", "Age", "Sex"])
df1

  Name  Age     Sex
0  AAA   33    male
1  BBB   28    None
2  CCC   45  female
3  DDD   41    male

In [23]:
# pandas.DataFrame 생성: 리스트와 딕셔너리가 같이 있는 경우
# pandas.DataFrame([ {딕셔너리1}, {딕셔너리2}, {딕셔너리3}, {딕셔너리4}])

df1=pd.DataFrame([{'Name':'AAA','Age':33, 'Sex':'male'},
                  {'Name':'BBB','Age':28, 'Sex':'male'},
                  {'Name':'CCC','Age':45, 'Sex':'female'}, 
                  {'Name':'DDD','Age':41, 'Sex':'male'}])
df1

  Name  Age     Sex
0  AAA   33    male
1  BBB   28    male
2  CCC   45  female
3  DDD   41    male